# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_fold) {transformation: [-1.149f,0f,-1.149f,0f,0f,1.625f,0f,0f,1.149f,0f,-1.149f,0.026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_blade) {transformation: [-1.0607f,0f,-1.0607f,0f,0f,1.5f,0f,0f,1.0607f,0f,-1.0607f,0.026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_1) {transformation: [-1.591f,0f,-1.591f,0f,0f,1.919f,0f,0f,1.591f,0f,-1.591f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_2) {transformation: [2.2097f,0f,-2.2097f,-0.5303f,0f,2.6653f,0f,0f,2.2097f,0f,2.2097f,1.3112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_3) {transformation: [0.7071f,0f,0.7071f,-1.8562f,0f,0.8529f,0f,0f,-0.7071f,0f,0.7071f,1.8562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_4) {transformation: [-1.591f,0f,1.591f,0f,0f,1.919f,0f,0f,-1.591f,0f,-1.591f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}