# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:fomalhaut/root/zzz/on_tick/select_locator_locator with entity @s data.locators.locator
function animated_java:fomalhaut/root/zzz/on_tick/select_locator_locator2 with entity @s data.locators.locator2