# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:fomalhaut/animations/animation.walk/zzz/apply_frame {frame: 28}
scoreboard players add @s aj.animation.walk.frame 1