# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 on passengers run data modify entity @s interpolation_duration set value 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.animation.blade_charge.frame
function animated_java:fomalhaut/animations/animation.blade_charge/zzz/apply_frame with storage aj:temp args
execute if score @s aj.animation.blade_charge.frame matches 134 run return run function animated_java:fomalhaut/animations/animation.blade_charge/stop
scoreboard players add @s aj.animation.blade_charge.frame 1