# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_pile_1) {transformation: [-1.0215f,0f,-2.0048f,0.3322f,0f,2.25f,0f,0f,2.0048f,0f,-1.0215f,0.2414f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_1) {transformation: [-1.4755f,0f,-2.8958f,1.6942f,0f,3.25f,0f,2.25f,2.8958f,0f,-1.4755f,-2.4317f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_1) {transformation: [-0.8512f,0f,-1.6706f,0.9281f,0f,1.875f,0f,1.5f,1.6706f,0f,-0.8512f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_2) {transformation: [2.7844f,0f,-1.4187f,0.1422f,0f,3.125f,0f,0f,1.4187f,0f,2.7844f,1.0787f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_2) {transformation: [2.8958f,0f,-1.4755f,-2.4362f,0f,3.25f,0f,2.25f,1.4755f,0f,2.8958f,-1.7081f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_2) {transformation: [1.6768f,0f,-0.8544f,-0.9281f,0f,1.8819f,0f,1.5f,0.8544f,0f,1.6768f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_3) {transformation: [0.454f,0f,0.891f,-1.5239f,0f,1f,0f,0f,-0.891f,0f,0.454f,2.0975f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_3) {transformation: [0.908f,0f,1.782f,-1.6942f,0f,2f,0f,2.25f,-1.782f,0f,0.908f,2.4317f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_3) {transformation: [0.908f,0f,1.782f,-0.9281f,0f,2f,0f,1.5f,-1.782f,0f,0.908f,0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_4) {transformation: [-2.0048f,0f,1.0215f,0f,0f,2.25f,0f,0f,-1.0215f,0f,-2.0048f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_4) {transformation: [-2.8958f,0f,1.4755f,2.673f,0f,3.25f,0f,2.25f,-1.4755f,0f,-2.8958f,1.362f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_4) {transformation: [-2.4503f,0f,1.2485f,0f,0f,2.75f,0f,1.125f,-1.2485f,0f,-2.4503f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}