# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_pile_1) {transformation: [-1.3225f,0f,-1.8203f,0.1566f,0f,2.25f,0f,0f,1.8203f,0f,-1.3225f,0.1338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_1) {transformation: [-1.9103f,0f,-2.6293f,1.92f,0f,3.25f,0f,2.25f,2.6293f,0f,-1.9103f,-2.2933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_1) {transformation: [-1.1021f,0f,-1.5169f,0.9281f,0f,1.875f,0f,1.5f,1.5169f,0f,-1.1021f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_2) {transformation: [2.5282f,0f,-1.8368f,-0.1849f,0f,3.125f,0f,0f,1.8368f,0f,2.5282f,1.2214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_2) {transformation: [2.6293f,0f,-1.9103f,-2.2956f,0f,3.25f,0f,2.25f,1.9103f,0f,2.6293f,-1.9344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_2) {transformation: [1.5225f,0f,-1.1062f,-0.9281f,0f,1.8819f,0f,1.5f,1.1062f,0f,1.5225f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_3) {transformation: [0.5878f,0f,0.809f,-1.6995f,0f,1f,0f,0f,-0.809f,0f,0.5878f,1.9899f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_3) {transformation: [1.1756f,0f,1.618f,-1.92f,0f,2f,0f,2.25f,-1.618f,0f,1.1756f,2.2933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_3) {transformation: [1.1756f,0f,1.618f,-0.9281f,0f,2f,0f,1.5f,-1.618f,0f,1.1756f,0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_4) {transformation: [-1.8203f,0f,1.3225f,0f,0f,2.25f,0f,0f,-1.3225f,0f,-1.8203f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_4) {transformation: [-2.6293f,0f,1.9103f,2.4271f,0f,3.25f,0f,2.25f,-1.9103f,0f,-2.6293f,1.7634f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_4) {transformation: [-2.2248f,0f,1.6164f,0f,0f,2.75f,0f,1.125f,-1.6164f,0f,-2.2248f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}