# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_pile_1) {transformation: [-0.2594f,0f,-2.235f,0.7768f,0f,0f,0f,0f,2.235f,0f,-0.2594f,0.3757f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_1) {transformation: [-0.3746f,0f,-3.2283f,1.1226f,0f,3.25f,0f,2.25f,3.2283f,0f,-0.3746f,-2.6043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_1) {transformation: [-0.2161f,0f,-1.8625f,0.9281f,0f,1.875f,0f,1.5f,1.8625f,0f,-0.2161f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_2) {transformation: [3.125f,0f,0f,0.9366f,0f,0f,0f,0f,0f,0f,3.125f,0.3741f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_2) {transformation: [3.25f,0f,0f,-2.6259f,0f,3.25f,0f,2.25f,0f,0f,3.25f,-0.9384f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_2) {transformation: [1.8819f,0f,0f,-0.9281f,0f,1.8819f,0f,1.5f,0f,0f,1.8819f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_3) {transformation: [0.6209f,0f,0.7839f,-1.743f,0f,0f,0f,0f,-0.7839f,0f,0.6209f,1.957f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_3) {transformation: [1.2418f,0f,1.5678f,-1.9758f,0f,2f,0f,2.25f,-1.5678f,0f,1.2418f,2.2509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_3) {transformation: [1.2418f,0f,1.5678f,-0.9281f,0f,2f,0f,1.5f,-1.5678f,0f,1.2418f,0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_4) {transformation: [-2.2483f,0f,-0.0878f,0f,0f,0f,0f,0f,0.0878f,0f,-2.2483f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_4) {transformation: [-3.2475f,0f,-0.1268f,2.9977f,0f,3.25f,0f,2.25f,0.1268f,0f,-3.2475f,-0.117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_4) {transformation: [-2.7479f,0f,-0.1073f,0f,0f,2.75f,0f,1.125f,0.1073f,0f,-2.7479f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}