# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_pile_1) {transformation: [0.0878f,0f,-2.2483f,0.9793f,0f,2.25f,0f,0f,2.2483f,0f,0.0878f,0.3834f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_1) {transformation: [0.1268f,0f,-3.2475f,0.8623f,0f,3.25f,0f,2.25f,3.2475f,0f,0.1268f,-2.6143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_1) {transformation: [0.0731f,0f,-1.8736f,0.9281f,0f,1.875f,0f,1.5f,1.8736f,0f,0.0731f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_2) {transformation: [3.125f,0f,0f,0.9366f,0f,3.125f,0f,0f,0f,0f,3.125f,0.3741f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_3) {transformation: [0.1153f,0f,0.9933f,-1.0794f,0f,1f,0f,0f,-0.9933f,0f,0.1153f,2.2318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_3) {transformation: [0.2305f,0f,1.9867f,-1.1226f,0f,2f,0f,2.25f,-1.9867f,0f,0.2305f,2.6043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_3) {transformation: [0.2305f,0f,1.9867f,-0.9281f,0f,2f,0f,1.5f,-1.9867f,0f,0.2305f,0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_4) {transformation: [-2.25f,0f,0f,0f,0f,2.25f,0f,0f,0f,0f,-2.25f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_4) {transformation: [-3.25f,0f,0f,3f,0f,3.25f,0f,2.25f,0f,0f,-3.25f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_4) {transformation: [-2.75f,0f,0f,0f,0f,2.75f,0f,1.125f,0f,0f,-2.75f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}