# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_pile_1) {transformation: [-0.352f,0f,-2.2223f,0.7228f,0f,2.25f,0f,0f,2.2223f,0f,-0.352f,0.3683f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_1) {transformation: [-0.5084f,0f,-3.21f,1.1921f,0f,3.25f,0f,2.25f,3.21f,0f,-0.5084f,-2.5948f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_1) {transformation: [-0.2933f,0f,-1.8519f,0.9281f,0f,1.875f,0f,1.5f,1.8519f,0f,-0.2933f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_2) {transformation: [3.0865f,0f,-0.4889f,0.7099f,0f,3.125f,0f,0f,0.4889f,0f,3.0865f,0.6497f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_2) {transformation: [3.21f,0f,-0.5084f,-2.6034f,0f,3.25f,0f,2.25f,0.5084f,0f,3.21f,-1.2039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_2) {transformation: [1.8587f,0f,-0.2944f,-0.9281f,0f,1.8819f,0f,1.5f,0.2944f,0f,1.8587f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_3) {transformation: [0.1564f,0f,0.9877f,-1.1334f,0f,1f,0f,0f,-0.9877f,0f,0.1564f,2.2244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_3) {transformation: [0.3129f,0f,1.9754f,-1.1921f,0f,2f,0f,2.25f,-1.9754f,0f,0.3129f,2.5948f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_3) {transformation: [0.3129f,0f,1.9754f,-0.9281f,0f,2f,0f,1.5f,-1.9754f,0f,0.3129f,0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_4) {transformation: [-2.2223f,0f,0.352f,0f,0f,2.25f,0f,0f,-0.352f,0f,-2.2223f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_4) {transformation: [-3.21f,0f,0.5084f,2.9631f,0f,3.25f,0f,2.25f,-0.5084f,0f,-3.21f,0.4693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_4) {transformation: [-2.7161f,0f,0.4302f,0f,0f,2.75f,0f,1.125f,-0.4302f,0f,-2.7161f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}