# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.fomalhaut.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'fomalhaut', 'function_path': 'animated_java:fomalhaut/animations/animation.launch_missile/set_frame'}
data remove storage aj:temp args
$execute store result storage aj:temp args.frame int 1 run scoreboard players set @s aj.animation.launch_missile.frame $(frame)
execute at @s run function animated_java:fomalhaut/animations/animation.launch_missile/zzz/set_frame with storage aj:temp args