# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.barrel_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_barrel_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.barrel_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_barrel_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.barrel_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_barrel_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.barrel_4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_barrel_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.gun_barrels] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_gun_barrels set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.gatling_head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_gatling_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.joint_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_joint_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.joint_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_joint_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.neck] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_neck set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.gatling] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_gatling set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.missile_rack] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_missile_rack set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.laser_cannon] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_laser_cannon set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.fold] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_fold set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.blade] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_blade set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.pile_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pile_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.leg_joint_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_joint_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.leg_1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.pile_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pile_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.leg_joint_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_joint_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.leg_2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.pile_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pile_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.leg_joint_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_joint_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.leg_3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.pile_4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_pile_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.leg_joint_4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_joint_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.leg_4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_leg_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.fomalhaut.node.root] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_root set from storage aj:uuid main.out