# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.fomalhaut.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'fomalhaut', 'function_path': 'animated_java:fomalhaut/animations/pause_all'}
tag @s remove aj.fomalhaut.animation.animation.walk.playing
tag @s remove aj.fomalhaut.animation.animation.rotation_right.playing
tag @s remove aj.fomalhaut.animation.animation.rotation_left.playing
tag @s remove aj.fomalhaut.animation.animation.extend.playing
tag @s remove aj.fomalhaut.animation.animation.fold.playing
tag @s remove aj.fomalhaut.animation.animation.blade_charge.playing
tag @s remove aj.fomalhaut.animation.animation.gatling.playing
tag @s remove aj.fomalhaut.animation.animation.laser_wipe.playing
tag @s remove aj.fomalhaut.animation.animation.laser_shot.playing
tag @s remove aj.fomalhaut.animation.animation.launch_missile.playing
tag @s remove aj.fomalhaut.animation.animation.stomp.playing
tag @s remove aj.fomalhaut.animation.animation.self_recovery.playing