# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_pile_1) {transformation: [-1.591f,0f,-1.591f,0f,0f,0f,0f,0f,1.591f,0f,-1.591f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_2) {transformation: [2.2942f,0f,-2.1218f,-0.4433f,0f,0f,0f,0f,2.1218f,0f,2.2942f,1.294f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_2) {transformation: [2.386f,0f,-2.2067f,-2.1675f,0f,3.25f,0f,2.25f,2.2067f,0f,2.386f,-2.0885f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_2) {transformation: [1.3816f,0f,-1.2778f,-0.9281f,0f,1.8819f,0f,1.5f,1.2778f,0f,1.3816f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_3) {transformation: [0.7071f,0f,0.7071f,-1.8562f,0f,0f,0f,0f,-0.7071f,0f,0.7071f,1.8562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_4) {transformation: [-1.591f,0f,1.591f,0f,0f,0f,0f,0f,-1.591f,0f,-1.591f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}