# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_pile_1) {transformation: [-2.1399f,0f,-0.6953f,-0.3202f,0f,2.25f,0f,0f,0.6953f,0f,-2.1399f,-0.5225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_1) {transformation: [-3.0909f,0f,-1.0043f,2.533f,0f,3.25f,0f,2.25f,1.0043f,0f,-3.0909f,-1.4495f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_1) {transformation: [-1.7832f,0f,-0.5794f,0.9281f,0f,1.875f,0f,1.5f,0.5794f,0f,-1.7832f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_2) {transformation: [0.9657f,0f,-2.9721f,-1.5903f,0f,3.125f,0f,0f,2.9721f,0f,0.9657f,1.2477f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_2) {transformation: [1.0043f,0f,-3.0909f,-1.4429f,0f,3.25f,0f,2.25f,3.0909f,0f,1.0043f,-2.546f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_2) {transformation: [0.5815f,0f,-1.7898f,-0.9281f,0f,1.8819f,0f,1.5f,1.7898f,0f,0.5815f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_3) {transformation: [0.9511f,0f,0.309f,-2.1763f,0f,1f,0f,0f,-0.309f,0f,0.9511f,1.3337f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_3) {transformation: [1.9021f,0f,0.618f,-2.533f,0f,2f,0f,2.25f,-0.618f,0f,1.9021f,1.4495f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_3) {transformation: [1.9021f,0f,0.618f,-0.9281f,0f,2f,0f,1.5f,-0.618f,0f,1.9021f,0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_4) {transformation: [-0.6953f,0f,2.1399f,0f,0f,2.25f,0f,0f,-2.1399f,0f,-0.6953f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_4) {transformation: [-1.0043f,0f,3.0909f,0.9271f,0f,3.25f,0f,2.25f,-3.0909f,0f,-1.0043f,2.8532f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_4) {transformation: [-0.8498f,0f,2.6154f,0f,0f,2.75f,0f,1.125f,-2.6154f,0f,-0.8498f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}