# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_pile_1) {transformation: [-1.5277f,0f,-1.6518f,0.0369f,0f,0f,0f,0f,1.6518f,0f,-1.5277f,0.0355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_1) {transformation: [-2.2067f,0f,-2.386f,2.0739f,0f,3.25f,0f,2.25f,2.386f,0f,-2.2067f,-2.167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_1) {transformation: [-1.2731f,0f,-1.3765f,0.9281f,0f,1.875f,0f,1.5f,1.3765f,0f,-1.2731f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_2) {transformation: [0.3602f,0f,-3.1042f,-2.0066f,0f,0f,0f,0f,3.1042f,0f,0.3602f,1.0742f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_2) {transformation: [0.3746f,0f,-3.2283f,-1.1135f,0f,3.25f,0f,2.25f,3.2283f,0f,0.3746f,-2.6158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_2) {transformation: [0.2169f,0f,-1.8694f,-0.9281f,0f,1.8819f,0f,1.5f,1.8694f,0f,0.2169f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_4) {transformation: [-1.397f,0f,1.7638f,0f,0f,0f,0f,0f,-1.7638f,0f,-1.397f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_4) {transformation: [-2.0179f,0f,2.5477f,1.8626f,0f,3.25f,0f,2.25f,-2.5477f,0f,-2.0179f,2.3517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_4) {transformation: [-1.7074f,0f,2.1557f,0f,0f,2.75f,0f,1.125f,-2.1557f,0f,-1.7074f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}