# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_pile_1) {transformation: [-1.7638f,0f,-1.397f,-0.1008f,0f,0f,0f,0f,1.397f,0f,-1.7638f,-0.1132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_1) {transformation: [-2.5477f,0f,-2.0179f,2.2509f,0f,3.25f,0f,2.25f,2.0179f,0f,-2.5477f,-1.9758f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_1) {transformation: [-1.4698f,0f,-1.1642f,0.9281f,0f,1.875f,0f,1.5f,1.1642f,0f,-1.4698f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_2) {transformation: [-0.1219f,0f,-3.1226f,-2.302f,0f,0f,0f,0f,3.1226f,0f,-0.1219f,0.8844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_2) {transformation: [-0.1268f,0f,-3.2475f,-0.8515f,0f,3.25f,0f,2.25f,3.2475f,0f,-0.1268f,-2.6242f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_2) {transformation: [-0.0734f,0f,-1.8805f,-0.9281f,0f,1.8819f,0f,1.5f,1.8805f,0f,-0.0734f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_3) {transformation: [0.679f,0f,0.7341f,-1.8192f,0f,0f,0f,0f,-0.7341f,0f,0.679f,1.8916f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_3) {transformation: [1.358f,0f,1.4683f,-2.0739f,0f,2f,0f,2.25f,-1.4683f,0f,1.358f,2.167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_3) {transformation: [1.358f,0f,1.4683f,-0.9281f,0f,2f,0f,1.5f,-1.4683f,0f,1.358f,0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_4) {transformation: [-0.2594f,0f,2.235f,0f,0f,0f,0f,0f,-2.235f,0f,-0.2594f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_4) {transformation: [-0.3746f,0f,3.2283f,0.3458f,0f,3.25f,0f,2.25f,-3.2283f,0f,-0.3746f,2.98f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_4) {transformation: [-0.317f,0f,2.7317f,0f,0f,2.75f,0f,1.125f,-2.7317f,0f,-0.317f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}