# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_pile_1) {transformation: [-2.25f,0f,0f,-0.3844f,0f,2.25f,0f,0f,0f,0f,-2.25f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_1) {transformation: [-3.25f,0f,0f,2.6156f,0f,3.25f,0f,2.25f,0f,0f,-3.25f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_1) {transformation: [-1.875f,0f,0f,0.9281f,0f,1.875f,0f,1.5f,0f,0f,-1.875f,-0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_pile_3) {transformation: [0.9992f,0f,-0.039f,-2.2396f,0f,1f,0f,0f,0.039f,0f,0.9992f,0.8769f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_joint_3) {transformation: [1.9985f,0f,-0.078f,-2.6143f,0f,2f,0f,2.25f,0.078f,0f,1.9985f,0.8623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_leg_3) {transformation: [1.9985f,0f,-0.078f,-0.9281f,0f,2f,0f,1.5f,0.078f,0f,1.9985f,0.9281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}