# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.animation.walk.frame dummy
scoreboard objectives add aj.animation.rotation_right.frame dummy
scoreboard objectives add aj.animation.rotation_left.frame dummy
scoreboard objectives add aj.animation.extend.frame dummy
scoreboard objectives add aj.animation.fold.frame dummy
scoreboard objectives add aj.animation.blade_charge.frame dummy
scoreboard objectives add aj.animation.gatling.frame dummy
scoreboard objectives add aj.animation.laser_wipe.frame dummy
scoreboard objectives add aj.animation.laser_shot.frame dummy
scoreboard objectives add aj.animation.launch_missile.frame dummy
scoreboard objectives add aj.animation.stomp.frame dummy
scoreboard objectives add aj.animation.self_recovery.frame dummy