# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.animation.walk.frame
scoreboard objectives remove aj.animation.rotation_right.frame
scoreboard objectives remove aj.animation.rotation_left.frame
scoreboard objectives remove aj.animation.extend.frame
scoreboard objectives remove aj.animation.fold.frame
scoreboard objectives remove aj.animation.blade_charge.frame
scoreboard objectives remove aj.animation.gatling.frame
scoreboard objectives remove aj.animation.laser_wipe.frame
scoreboard objectives remove aj.animation.laser_shot.frame
scoreboard objectives remove aj.animation.launch_missile.frame
scoreboard objectives remove aj.animation.stomp.frame
scoreboard objectives remove aj.animation.self_recovery.frame
tellraw @a [[{"text":"\n[","color":"gray"},{"text":"AJ","color":"aqua"},"] ",[{"text":"(from ","color":"gray","italic":true},"fomalhaut",")"]," -> "],{"text":"Successfully removed known animation scoreboard objectives.","color":"red"},{"text":"\nIf you have exported multiple times you may have to manually remove some objectives from previous exports manually, as Animated Java can only remove the latest export's objectives.","color":"gray","italic":true},["\n"]]