# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fomalhaut.root] run return 0
execute on passengers if entity @s[tag=aj.fomalhaut.data] unless data entity @s {data:{rigHash: 'beec7ac15fc7ea676fa9d024a2a86fe12e5f51c67755746ab8477abf0b027593'}} on vehicle run function animated_java:fomalhaut/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1