# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.fomalhaut.root] at @s run return 0
execute unless score @s aj.is_rig_loaded matches 1 at @s run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.fomalhaut.animation.animation.walk.playing] at @s run function animated_java:fomalhaut/animations/animation.walk/zzz/on_tick
execute if entity @s[tag=aj.fomalhaut.animation.animation.rotation_right.playing] at @s run function animated_java:fomalhaut/animations/animation.rotation_right/zzz/on_tick
execute if entity @s[tag=aj.fomalhaut.animation.animation.rotation_left.playing] at @s run function animated_java:fomalhaut/animations/animation.rotation_left/zzz/on_tick
execute if entity @s[tag=aj.fomalhaut.animation.animation.extend.playing] at @s run function animated_java:fomalhaut/animations/animation.extend/zzz/on_tick
execute if entity @s[tag=aj.fomalhaut.animation.animation.fold.playing] at @s run function animated_java:fomalhaut/animations/animation.fold/zzz/on_tick
execute if entity @s[tag=aj.fomalhaut.animation.animation.blade_charge.playing] at @s run function animated_java:fomalhaut/animations/animation.blade_charge/zzz/on_tick
execute if entity @s[tag=aj.fomalhaut.animation.animation.gatling.playing] at @s run function animated_java:fomalhaut/animations/animation.gatling/zzz/on_tick
execute if entity @s[tag=aj.fomalhaut.animation.animation.laser_wipe.playing] at @s run function animated_java:fomalhaut/animations/animation.laser_wipe/zzz/on_tick
execute if entity @s[tag=aj.fomalhaut.animation.animation.laser_shot.playing] at @s run function animated_java:fomalhaut/animations/animation.laser_shot/zzz/on_tick
execute if entity @s[tag=aj.fomalhaut.animation.animation.launch_missile.playing] at @s run function animated_java:fomalhaut/animations/animation.launch_missile/zzz/on_tick
execute if entity @s[tag=aj.fomalhaut.animation.animation.stomp.playing] at @s run function animated_java:fomalhaut/animations/animation.stomp/zzz/on_tick
execute if entity @s[tag=aj.fomalhaut.animation.animation.self_recovery.playing] at @s run function animated_java:fomalhaut/animations/animation.self_recovery/zzz/on_tick
execute on passengers if entity @s[tag=aj.fomalhaut.data] at @s run function animated_java:fomalhaut/root/zzz/on_tick/locators_and_cameras
execute at @s on passengers run rotate @s ~ ~